# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activesupport/all/activesupport.rbi
#
# activesupport-8.0.2.1

class Module
end
module ActiveSupport
  extend ActiveSupport::Autoload
  extend ActiveSupport::LazyLoadHooks
end
class ActiveSupport::DelegationError < NoMethodError
end
module ActiveSupport::Delegation
end
module ActiveSupport::JSON
end
module ActiveSupport::BigDecimalWithDefaultFormat
end
class Hash
  include ActiveSupport::DeepMergeable
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class Object < BasicObject
  include ActiveSupport::ToJsonWithActiveSupportEncoder
  include ActiveSupport::Tryable
end
module ActiveSupport::DeepMergeable
end
module ActiveSupport::LazyLoadHooks
end
module ActiveSupport::Inflector
  extend ActiveSupport::Inflector
  extend ActiveSupport::Inflector
end
class ActiveSupport::Inflector::Inflections
end
class ActiveSupport::Inflector::Inflections::Uncountables < Array
end
class ActiveSupport::TimeZone
  include Comparable
end
class Time
  include DateAndTime::Calculations
  include DateAndTime::Zones
end
class DateTime < Date
end
module DateAndTime
end
module DateAndTime::Zones
end
class Date
  include DateAndTime::Calculations
  include DateAndTime::Zones
end
module ActiveSupport::ToJsonWithActiveSupportEncoder
end
class TrueClass
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class String
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class NilClass
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class Integer < Numeric
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class Float < Numeric
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class FalseClass
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class Array
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
module Enumerable
  include ActiveSupport::ToJsonWithActiveSupportEncoder
end
class Data
end
class Struct
end
class Symbol
end
class Numeric
end
class BigDecimal < Numeric
end
class Regexp
end
class IO
end
class Range
end
class URI::Generic
end
class Pathname
end
class Process::Status
end
class Exception
end
module ActiveSupport::JSON::Encoding
end
class ActiveSupport::JSON::Encoding::JSONGemEncoder
end
module ActiveSupport::Autoload
end
module ActiveSupport::VERSION
end
module ActiveSupport::Concern
end
class ActiveSupport::Concern::MultipleIncludedBlocks < StandardError
end
class ActiveSupport::Concern::MultiplePrependBlocks < StandardError
end
module ActiveSupport::LoggerThreadSafeLevel
  extend ActiveSupport::Concern
end
module ActiveSupport::LoggerSilence
  extend ActiveSupport::Concern
end
class ActiveSupport::Logger < Logger
  include ActiveSupport::LoggerSilence
  include ActiveSupport::LoggerThreadSafeLevel
end
class ActiveSupport::Logger::SimpleFormatter < Logger::Formatter
end
class ActiveSupport::BroadcastLogger
  include ActiveSupport::LoggerSilence
  include ActiveSupport::LoggerThreadSafeLevel
end
module DateAndTime::Compatibility
end
class ActiveSupport::ErrorReporter
end
class ActiveSupport::ErrorReporter::UnexpectedError < Exception
end
module ActiveSupport::Multibyte
end
class ActiveSupport::Duration
end
class ActiveSupport::Duration::Scalar < Numeric
end
class ActiveSupport::TimeWithZone
  include Comparable
end
module ActiveSupport::Tryable
end
class Delegator < BasicObject
  include ActiveSupport::Tryable
end
module DateAndTime::Calculations
end
module ActiveSupport::CoreExt
end
module ActiveSupport::CoreExt::ERBUtil
end
module ActiveSupport::CoreExt::ERBUtilPrivate
  include ActiveSupport::CoreExt::ERBUtil
end
class ERB
end
module ERB::Util
end
module ActiveSupport::Multibyte::Unicode
  extend ActiveSupport::Multibyte::Unicode
end
class ActiveSupport::SafeBuffer < String
end
class ActiveSupport::SafeBuffer::SafeConcatError < StandardError
end
class ActiveSupport::StringInquirer < String
end
class ActiveSupport::EnvironmentInquirer < ActiveSupport::StringInquirer
end
