# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/bootsnap/all/bootsnap.rbi
#
# bootsnap-1.18.6

module Bootsnap
  extend Bootsnap
end
module Bootsnap::ExplicitRequire
end
module Bootsnap::LoadPathCache
end
module Bootsnap::LoadPathCache::PathScanner
end
class Bootsnap::LoadPathCache::Path
end
class Bootsnap::LoadPathCache::Cache
end
class Bootsnap::LoadPathCache::Store
end
class Bootsnap::LoadPathCache::Store::NestedTransactionError < StandardError
end
class Bootsnap::LoadPathCache::Store::SetOutsideTransactionNotAllowed < StandardError
end
module Bootsnap::LoadPathCache::ChangeObserver
end
module Bootsnap::LoadPathCache::ChangeObserver::ArrayMixin
end
class Bootsnap::LoadPathCache::LoadedFeaturesIndex
end
module Bootsnap::CompileCache
end
class Bootsnap::CompileCache::Error < StandardError
end
class Bootsnap::InvalidConfiguration < StandardError
end
module Kernel
end
module Bootsnap::CompileCache::ISeq
end
module Bootsnap::CompileCache::ISeq::InstructionSequenceMixin
end
module Bootsnap::CompileCache::YAML
end
class Bootsnap::CompileCache::YAML::Uncompilable < StandardError
end
class Bootsnap::CompileCache::YAML::UnsupportedTags < Bootsnap::CompileCache::YAML::Uncompilable
end
module InvalidName___Class_0x00___EncodingAwareSymbols_16
  extend InvalidName___Class_0x00___EncodingAwareSymbols_16
end
module Bootsnap::CompileCache::YAML::Psych4
  extend Bootsnap::CompileCache::YAML::Psych4
end
module Bootsnap::CompileCache::YAML::Psych4::UnsafeLoad
  extend Bootsnap::CompileCache::YAML::Psych4::UnsafeLoad
end
module Bootsnap::CompileCache::YAML::Psych4::SafeLoad
  extend Bootsnap::CompileCache::YAML::Psych4::SafeLoad
end
module Bootsnap::CompileCache::YAML::Psych4::Patch
end
module Bootsnap::CompileCache::YAML::Psych3
  extend Bootsnap::CompileCache::YAML::Psych3
end
module Bootsnap::CompileCache::YAML::Psych3::Patch
end
module Bootsnap::CompileCache::JSON
end
module Bootsnap::CompileCache::JSON::Patch
end
class Bootsnap::CompileCache::YAML::NoTagsVisitor < Psych::Visitors::NoAliasRuby
end
