# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cli-ui/all/cli-ui.rbi
#
# cli-ui-2.4.0

module CLI
end
module CLI::UI
  extend T::Sig
end
class CLI::UI::OS
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module CLI::UI::ANSI
  extend T::Sig
end
class CLI::UI::Color
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::Color::InvalidColorName < ArgumentError
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module CLI::UI::Spinner
  extend T::Sig
end
class CLI::UI::WorkQueue
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::WorkQueue::Future
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::Spinner::SpinGroup
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::Spinner::SpinGroup::Task
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::ReentrantMutex < Thread::Mutex
end
module CLI::UI::StdoutRouter
end
class CLI::UI::StdoutRouter::Writer
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::StdoutRouter::Capture
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CLI::UI::StdoutRouter::Capture::BlockingInput
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class InvalidName___Class_0x00___NotEnabled_15 < StandardError
end
