# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `code_teams` gem.
# Please instead update this file by running `bin/tapioca gem code_teams`.


class CodeTeams::IncorrectPublicApiUsageError < ::StandardError; end

class CodeTeams::Plugins::Identity::IdentityStruct < ::Struct
  # Returns the value of attribute name
  #
  # @return [Object] the current value of name
  def name; end

  # Sets the attribute name
  #
  # @param value [Object] the value to set the attribute name to.
  # @return [Object] the newly set value
  def name=(_); end

  class << self
    def [](*_arg0); end
    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end
  end
end

# source://code_teams//lib/code_teams.rb#17
CodeTeams::UNKNOWN_TEAM_STRING = T.let(T.unsafe(nil), String)

module CodeTeams::Utils
  private

  # source://code_teams//lib/code_teams/utils.rb#13
  def demodulize(string); end

  # source://code_teams//lib/code_teams/utils.rb#5
  def underscore(string); end

  class << self
    # source://code_teams//lib/code_teams/utils.rb#13
    def demodulize(string); end

    # source://code_teams//lib/code_teams/utils.rb#5
    def underscore(string); end
  end
end
