# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/docile/all/docile.rbi
#
# docile-1.4.1

module Docile
  extend Docile::Execution
end
module Docile::Execution
end
class Docile::FallbackContextProxy
end
class Docile::ChainingFallbackContextProxy < Docile::FallbackContextProxy
end
module Docile::BacktraceFilter
end
