# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erb/all/erb.rbi
#
# erb-5.0.2

class ERB
end
class ERB::Compiler
end
class ERB::Compiler::PercentLine
end
class ERB::Compiler::Scanner
end
class ERB::Compiler::TrimScanner < ERB::Compiler::Scanner
end
class ERB::Compiler::SimpleScanner < ERB::Compiler::Scanner
end
class ERB::Compiler::ExplicitScanner < ERB::Compiler::Scanner
end
class ERB::Compiler::Buffer
end
module ERB::DefMethod
end
module ERB::Util
  include ERB::Escape
end
