# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/i18n/all/i18n.rbi
#
# i18n-1.14.7

module I18n
  extend I18n::Base
end
module I18n::Utils
end
class I18n::ExceptionHandler
end
class I18n::ArgumentError < ArgumentError
end
class I18n::Disabled < I18n::ArgumentError
end
class I18n::InvalidLocale < I18n::ArgumentError
end
class I18n::InvalidLocaleData < I18n::ArgumentError
end
class I18n::MissingTranslation < I18n::ArgumentError
  include I18n::MissingTranslation::Base
end
module I18n::MissingTranslation::Base
end
class I18n::MissingTranslationData < I18n::ArgumentError
  include I18n::MissingTranslation::Base
end
class I18n::InvalidPluralizationData < I18n::ArgumentError
end
class I18n::MissingInterpolationArgument < I18n::ArgumentError
end
class I18n::ReservedInterpolationKey < I18n::ArgumentError
end
class I18n::UnknownFileType < I18n::ArgumentError
end
class I18n::UnsupportedMethod < I18n::ArgumentError
end
class I18n::InvalidFilenames < I18n::ArgumentError
end
module I18n::Base
end
module I18n::Backend
end
module I18n::Backend::Transliterator
end
class I18n::Backend::Transliterator::ProcTransliterator
end
class I18n::Backend::Transliterator::HashTransliterator
end
module I18n::Backend::Base
  include I18n::Backend::Transliterator
end
module I18n::Backend::InterpolationCompiler
end
module I18n::Backend::InterpolationCompiler::Compiler
  extend I18n::Backend::InterpolationCompiler::Compiler
end
module I18n::Backend::Cache
end
module I18n::Backend::CacheFile
end
module I18n::Backend::Cascade
end
class I18n::Backend::Chain
  include I18n::Backend::Chain::Implementation
end
module I18n::Backend::Chain::Implementation
  include I18n::Backend::Base
end
module I18n::Backend::Fallbacks
end
module I18n::Backend::Flatten
end
module I18n::Gettext
end
module GetText
end
class GetText::PoParser < Racc::Parser
end
module I18n::Backend::Gettext
end
class I18n::Backend::Gettext::PoData < Hash
end
class I18n::Config
end
class I18n::Backend::KeyValue
  include I18n::Backend::KeyValue::Implementation
end
module I18n::Backend::KeyValue::Implementation
  include I18n::Backend::Base
end
class I18n::Backend::KeyValue::SubtreeProxy
end
module I18n::Backend::Memoize
end
module I18n::Backend::Metadata
end
module I18n::Backend::Pluralization
end
class I18n::Backend::Simple
  include I18n::Backend::Simple::Implementation
end
module I18n::Backend::Simple::Implementation
  include I18n::Backend::Base
end
module I18n::Gettext::Helpers
end
module I18n::Locale
end
class I18n::Locale::Fallbacks < Hash
end
module I18n::Locale::Tag
end
module I18n::Locale::Tag::Parents
end
class I18n::Locale::Tag::Rfc4646 < Anonymous_Struct_8
  include I18n::Locale::Tag::Parents
end
module I18n::Locale::Tag::Rfc4646::Parser
end
class I18n::Locale::Tag::Simple
  include I18n::Locale::Tag::Parents
end
module I18n::Tests
end
class I18n::Middleware
end
