# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/lint_roller/all/lint_roller.rbi
#
# lint_roller-1.1.0

module LintRoller
end
class LintRoller::Plugin
end
class LintRoller::Error < StandardError
end
module LintRoller::Support
end
class LintRoller::Support::MergesUpstreamMetadata
end
