# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/money/all/money.rbi
#
# money-6.19.0

class Money
  extend Money::Constructors
  include Comparable
  include Money::Arithmetic
end
class Money::Currency
  extend Enumerable
  extend Money::Currency::Heuristics
  include Comparable
end
module Money::Currency::Loader
end
module Money::Currency::Heuristics
end
class Money::Currency::MissingAttributeError < StandardError
end
class Money::Currency::UnknownCurrency < ArgumentError
end
module Money::Bank
end
class Money::Bank::Error < StandardError
end
class Money::Bank::UnknownRate < Money::Bank::Error
end
class Money::Bank::Base
end
module Money::RatesStore
end
class Money::RatesStore::Memory
end
class Money::Bank::UnknownRateFormat < StandardError
end
class Money::Bank::VariableExchange < Money::Bank::Base
end
class Money::Bank::DifferentCurrencyError < Money::Bank::Error
end
class Money::Bank::SingleCurrency < Money::Bank::Base
end
module Money::Arithmetic
end
module Money::Constructors
end
class Money::FormattingRules
end
class Money::Formatter
end
class Money::Allocation
end
module Money::LocaleBackend
end
class Money::LocaleBackend::NotSupported < StandardError
end
class Money::LocaleBackend::Unknown < ArgumentError
end
class Money::LocaleBackend::Base
end
class Money::LocaleBackend::I18n < Money::LocaleBackend::Base
end
class Money::LocaleBackend::Legacy < Money::LocaleBackend::Base
end
class Money::LocaleBackend::Currency < Money::LocaleBackend::Base
end
class Money::UndefinedSmallestDenomination < StandardError
end
