# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/msgpack/all/msgpack.rbi
#
# msgpack-1.8.0

module MessagePack
end
class MessagePack::Buffer
end
class MessagePack::Packer
end
class MessagePack::Unpacker
end
class MessagePack::Factory
end
class MessagePack::Factory::Pool
end
class MessagePack::Factory::Pool::MemberPool
end
class Symbol
  include MessagePack::CoreExt
end
module MessagePack::CoreExt
end
class NilClass
  include MessagePack::CoreExt
end
class TrueClass
  include MessagePack::CoreExt
end
class FalseClass
  include MessagePack::CoreExt
end
class Float < Numeric
  include MessagePack::CoreExt
end
class String
  include MessagePack::CoreExt
end
class Array
  include MessagePack::CoreExt
end
class Hash
  include MessagePack::CoreExt
end
class Integer < Numeric
  include MessagePack::CoreExt
end
class MessagePack::ExtensionValue < Struct
  include MessagePack::CoreExt
end
class MessagePack::Timestamp
end
module MessagePack::Time
end
