# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/packs/all/packs.rbi
#
# packs-0.2.0

module Packs
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Packs::Private
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::Private::FileMoveOperation < T::Struct
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
module Packs::Private::PackRelationshipAnalyzer
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Packs::Private::InteractiveCli
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::Private::InteractiveCli::TeamSelector
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::Private::InteractiveCli::PackSelector
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::Private::InteractiveCli::PackDirectorySelector
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::Private::InteractiveCli::FileSelector
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Packs::Private::InteractiveCli::UseCases
end
module Packs::Private::InteractiveCli::UseCases::Interface
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::Private::InteractiveCli::UseCases::Create
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::Move
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::MovePack
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::AddDependency
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::GetInfo
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::Query
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::MakePublic
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::Rename
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::Check
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::Update
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::Validate
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
class Packs::Private::InteractiveCli::UseCases::LintPackageYmlFiles
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::Private::InteractiveCli::UseCases::Interface
end
module Packs::PerFileProcessorInterface
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::RubocopPostProcessor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::PerFileProcessorInterface
end
class Packs::UpdateReferencesPostProcessor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::PerFileProcessorInterface
end
class Packs::CodeOwnershipPostProcessor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include Packs::PerFileProcessorInterface
end
module Packs::Logging
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
module Packs::UserEventLogger
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::DefaultUserEventLogger
  include Packs::UserEventLogger
end
class Packs::Configuration
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class Packs::CLI < Thor
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
