# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `packs` gem.
# Please instead update this file by running `bin/tapioca gem packs`.


# source://packs//lib/packs/cli.rb#42
Packs::CLI::POSIBLE_TYPES = T.let(T.unsafe(nil), Array)

class Packs::Configuration
  # source://packs//lib/packs/configuration.rb#30
  sig { void }
  def initialize; end

  # source://packs//lib/packs/configuration.rb#43
  sig { void }
  def bust_cache!; end

  # source://packs//lib/packs/configuration.rb#48
  sig { returns(T::Boolean) }
  def default_enforce_dependencies; end

  # source://packs//lib/packs/configuration.rb#38
  sig { returns(T::Boolean) }
  def enforce_dependencies; end

  # source://packs//lib/packs/configuration.rb#14
  sig { params(enforce_dependencies: T::Boolean).void }
  def enforce_dependencies=(enforce_dependencies); end

  # source://packs//lib/packs/configuration.rb#27
  sig { returns(T.proc.params(output: ::String).void) }
  def on_package_todo_lint_failure; end

  # @return [OnPackageTodoLintFailure]
  #
  # source://packs//lib/packs/configuration.rb#27
  def on_package_todo_lint_failure=(_arg0); end

  # source://packs//lib/packs/configuration.rb#53
  sig { returns(::Pathname) }
  def readme_template_pathname; end

  # source://packs//lib/packs/configuration.rb#20
  sig { returns(T::Boolean) }
  def use_pks; end

  # @return [Boolean]
  #
  # source://packs//lib/packs/configuration.rb#20
  def use_pks=(_arg0); end

  # source://packs//lib/packs/configuration.rb#17
  sig { returns(::Packs::UserEventLogger) }
  def user_event_logger; end

  # @return [UserEventLogger]
  #
  # source://packs//lib/packs/configuration.rb#17
  def user_event_logger=(_arg0); end
end

# source://packs//lib/packs/configuration.rb#10
Packs::Configuration::CONFIGURATION_PATHNAME = T.let(T.unsafe(nil), Pathname)

# source://packs//lib/packs/configuration.rb#11
Packs::Configuration::DEFAULT_README_TEMPLATE_PATHNAME = T.let(T.unsafe(nil), Pathname)

# source://packs//lib/packs/configuration.rb#22
Packs::Configuration::OnPackageTodoLintFailure = T.type_alias { T.proc.params(output: ::String).void }

class Packs::DefaultUserEventLogger
  include ::Packs::UserEventLogger
end

# source://packs//lib/packs/private.rb#550
Packs::Private::PackageTodoFiles = T.type_alias { T::Hash[::String, T.nilable(::String)] }
