# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `packs-specification` gem.
# Please instead update this file by running `bin/tapioca gem packs-specification`.


# source://packs-specification//lib/packs-specification.rb#13
Packs::PACKAGE_FILE = T.let(T.unsafe(nil), String)

# source://packs-specification//lib/packs/specification/configuration.rb#7
Packs::Specification::Configuration::CONFIGURATION_PATHNAME = T.let(T.unsafe(nil), Pathname)

# source://packs-specification//lib/packs/specification/configuration.rb#9
Packs::Specification::Configuration::DEFAULT_PACK_PATHS = T.let(T.unsafe(nil), Array)
