# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/packs-specification/all/packs-specification.rbi
#
# packs-specification-0.0.10

module Packs
  def self.all(*args, **, &blk); end
  def self.find(*args, **, &blk); end
  def self.for_file(*args, **, &blk); end
end
class Packs::Pack < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def is_gem?(*args, **, &blk); end
  def last_name(*args, **, &blk); end
  def metadata(*args, **, &blk); end
  def name; end
  def path; end
  def raw_hash; end
  def relative_path; end
  def self.from(*args, **, &blk); end
  def self.inherited(s); end
  def yml(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
module Packs::Specification
  def self.all(*args, **, &blk); end
  def self.bust_cache!(*args, **, &blk); end
  def self.config(*args, **, &blk); end
  def self.find(*args, **, &blk); end
  def self.for_file(*args, **, &blk); end
  def self.package_glob_patterns(*args, **, &blk); end
  def self.packs_by_name(*args, **, &blk); end
  def self.root(*args, **, &blk); end
  extend T::Sig
end
class Packs::Specification::Configuration < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def pack_paths; end
  def pack_paths=(val); end
  def self.fetch(*args, **, &blk); end
  def self.inherited(s); end
  def self.pack_paths(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
