# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/packwerk/all/packwerk.rbi
#
# packwerk-3.2.3

module Packwerk
  extend ActiveSupport::Autoload
end
module Packwerk::OutputStyles
  extend ActiveSupport::Autoload
end
module Packwerk::Formatters
  extend ActiveSupport::Autoload
end
module Packwerk::Validators
  extend ActiveSupport::Autoload
end
module Packwerk::Generators
  extend ActiveSupport::Autoload
end
module Packwerk::ReferenceChecking
  extend ActiveSupport::Autoload
end
module Packwerk::ReferenceChecking::Checkers
  extend ActiveSupport::Autoload
end
