# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pastel/all/pastel.rbi
#
# pastel-0.8.0

module Pastel
end
class Pastel::AliasImporter
end
module Pastel::ANSI
end
class Pastel::Color
  include Pastel::ANSI
end
class Pastel::Detached
end
class Pastel::ColorResolver
end
class Pastel::ColorParser
  include Pastel::ANSI
end
class Pastel::DecoratorChain
  include Enumerable
end
class Pastel::Delegator
  extend Forwardable
end
class Pastel::InvalidAttributeNameError < ArgumentError
end
class Pastel::InvalidAliasNameError < ArgumentError
end
