# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rspec-core/all/rspec-core.rbi
#
# rspec-core-3.13.5

module RSpec
end
module RSpec::Core
end
module RSpec::Core::SharedContext
end
class RSpec::Core::ExampleStatusPersister
end
class RSpec::Core::ExampleStatusMerger
end
class RSpec::Core::ExampleStatusDumper
end
class RSpec::Core::ExampleStatusParser
end
class RSpec::Core::Profiler
end
class RSpec::Core::DidYouMean
end
module RSpec::Core::Formatters
end
class RSpec::Core::Formatters::BaseFormatter
end
class RSpec::Core::Formatters::BaseTextFormatter < RSpec::Core::Formatters::BaseFormatter
end
class RSpec::Core::Formatters::DocumentationFormatter < RSpec::Core::Formatters::BaseTextFormatter
end
class RSpec::Core::Formatters::HtmlPrinter
  include ERB::Util
end
class RSpec::Core::Formatters::HtmlFormatter < RSpec::Core::Formatters::BaseFormatter
end
class RSpec::Core::Formatters::FallbackMessageFormatter
end
class RSpec::Core::Formatters::ProgressFormatter < RSpec::Core::Formatters::BaseTextFormatter
end
class RSpec::Core::Formatters::ProfileFormatter
end
class RSpec::Core::Formatters::JsonFormatter < RSpec::Core::Formatters::BaseFormatter
end
module RSpec::Core::Bisect
end
class RSpec::Core::Bisect::BisectFailedError < StandardError
end
class RSpec::Core::Bisect::Notifier
end
class RSpec::Core::Bisect::Channel
end
class RSpec::Core::Formatters::BaseBisectFormatter
end
class RSpec::Core::Formatters::BisectDRbFormatter < RSpec::Core::Formatters::BaseBisectFormatter
end
class RSpec::Core::Formatters::FailureListFormatter < RSpec::Core::Formatters::BaseFormatter
end
module RSpec::Core::MockingAdapters
end
module RSpec::Core::MockingAdapters::RSpec
  include RSpec::Mocks::ExampleMethods
  include RSpec::Mocks::ExampleMethods::ExpectHost
end
