# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-performance/all/rubocop-performance.rbi
#
# rubocop-performance-1.25.0

module RuboCop
end
module RuboCop::Performance
end
module RuboCop::Performance::Version
end
class RuboCop::Performance::Plugin < LintRoller::Plugin
end
module RuboCop::Cop
end
module RuboCop::Cop::RegexpMetacharacter
end
module RuboCop::Cop::SortBlock
  extend RuboCop::AST::NodePattern::Macros
  include RuboCop::Cop::RangeHelp
end
module RuboCop::Cop::Performance
end
class RuboCop::Cop::Performance::AncestorsInclude < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::ArraySemiInfiniteRangeSlice < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::BigDecimalWithNumericArgument < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
end
class RuboCop::Cop::Performance::BindCall < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::BlockGivenWithExplicitBlock < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::Caller < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::CaseWhenSplat < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::Alignment
  include RuboCop::Cop::CommentsHelp
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::Casecmp < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::CollectionLiteralInLoop < RuboCop::Cop::Base
end
class RuboCop::Cop::Performance::CompareWithBlock < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::ConcurrentMonotonicTime < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::ConstantRegexp < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::Count < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::DeletePrefix < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RegexpMetacharacter
end
class RuboCop::Cop::Performance::DeleteSuffix < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RegexpMetacharacter
end
class RuboCop::Cop::Performance::Detect < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::DoubleStartEndWith < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::EndWith < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RegexpMetacharacter
end
class RuboCop::Cop::Performance::FixedSize < RuboCop::Cop::Base
end
class RuboCop::Cop::Performance::FlatMap < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::InefficientHashSearch < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::MapCompact < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::MapMethodChain < RuboCop::Cop::Base
  include RuboCop::Cop::IgnoredNode
end
class RuboCop::Cop::Performance::MethodObjectAsBlock < RuboCop::Cop::Base
end
class RuboCop::Cop::Performance::OpenStruct < RuboCop::Cop::Base
end
class RuboCop::Cop::Performance::RangeInclude < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::IoReadlines < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::RedundantBlockCall < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::RedundantEqualityComparisonBlock < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
end
class RuboCop::Cop::Performance::RedundantMatch < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::RedundantMerge < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::Alignment
end
class RuboCop::Cop::Performance::RedundantMerge::EachWithObjectInspector
  extend RuboCop::AST::NodePattern::Macros
end
class RuboCop::Cop::Performance::RedundantSortBlock < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::SortBlock
end
class RuboCop::Cop::Performance::RedundantSplitRegexpArgument < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::RedundantStringChars < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::RegexpMatch < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
end
class RuboCop::Cop::Performance::ReverseEach < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::ReverseFirst < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::SelectMap < RuboCop::Cop::Base
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::Size < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::SortReverse < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::SortBlock
end
class RuboCop::Cop::Performance::Squeeze < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::StringBytesize < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::StartWith < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RegexpMetacharacter
end
class RuboCop::Cop::Performance::StringIdentifierArgument < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::StringInclude < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::StringReplacement < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::Sum < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Performance::TimesMap < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::UnfreezeString < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
  extend RuboCop::Cop::TargetRubyVersion
end
class RuboCop::Cop::Performance::UriDefaultParser < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
class RuboCop::Cop::Performance::ChainArrayAllocation < RuboCop::Cop::Base
end
class RuboCop::Cop::Performance::ZipWithoutBlock < RuboCop::Cop::Base
  extend RuboCop::Cop::AutoCorrector
end
