# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby_parser/all/ruby_parser.rbi
#
# ruby_parser-3.21.1

class RubyLexer
  include RubyLexer::SSWrapper
  include RubyLexer::State::Values
end
class RubyLexer::LexerError < StandardError
end
class RubyLexer::ScanError < RubyLexer::LexerError
end
class RubyLexer::State
  include RubyLexer::State::Values
end
module RubyLexer::State::Values
end
module RubyLexer::SSWrapper
end
module RubyLexer::SSStackish
end
class Regexp
end
class String
end
class Sexp < Array
end
class RPStringScanner < StringScanner
end
module RubyParserStuff
end
class RubyParserStuff::Keyword
  include RubyLexer::State::Values
end
class RubyParserStuff::Keyword::KWtable
end
class RubyParserStuff::Environment
end
class RubyParserStuff::StackState
end
class Ruby20Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby21Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby22Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby23Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby24Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby25Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby26Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby27Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby30Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby31Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby32Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class Ruby33Parser < RubyParser::Parser
  include RubyLexer::State::Values
end
class RubyParser
end
class RubyParser::Parser < Racc::Parser
  include RubyParserStuff
end
class RubyParser::SyntaxError < RuntimeError
end
class RubyParser::V33 < Ruby33Parser
end
class RubyParser::V32 < Ruby32Parser
end
class RubyParser::V31 < Ruby31Parser
end
class RubyParser::V30 < Ruby30Parser
end
class RubyParser::V27 < Ruby27Parser
end
class RubyParser::V26 < Ruby26Parser
end
class RubyParser::V25 < Ruby25Parser
end
class RubyParser::V24 < Ruby24Parser
end
class RubyParser::V23 < Ruby23Parser
end
class RubyParser::V22 < Ruby22Parser
end
class RubyParser::V21 < Ruby21Parser
end
class RubyParser::V20 < Ruby20Parser
end
