# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sexp_processor/all/sexp_processor.rbi
#
# sexp_processor-4.17.4

class Sexp < Array
end
class Sexp::Matcher < Sexp
end
class Sexp::Matcher::Parser
end
class Sexp::Wild < Sexp::Matcher
end
class Sexp::Remaining < Sexp::Matcher
end
class Sexp::Any < Sexp::Matcher
end
class Sexp::All < Sexp::Matcher
end
class Sexp::Not < Sexp::Matcher
end
class Sexp::Child < Sexp::Matcher
end
class Sexp::Atom < Sexp::Matcher
end
class Sexp::Pattern < Sexp::Matcher
end
class Sexp::Klass < Sexp::Pattern
end
class Sexp::Type < Sexp::Matcher
end
class Sexp::Include < Sexp::Matcher
end
class Sexp::Sibling < Sexp::Matcher
end
class Sexp::MatchCollection < Array
end
class SexpProcessor
end
class SexpProcessor::Environment
end
class SexpInterpreter < SexpProcessor
end
class MethodBasedSexpProcessor < SexpProcessor
end
class Object < BasicObject
end
class SexpProcessorError < StandardError
end
class UnsupportedNodeError < SexpProcessorError
end
class UnknownNodeError < SexpProcessorError
end
class NotEmptyError < SexpProcessorError
end
class SexpTypeError < SexpProcessorError
end
