# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sexp_processor/all/sexp_processor.rbi
#
# sexp_processor-4.17.4

class SexpProcessor
end
class SexpProcessor::Environment
end
class SexpInterpreter < SexpProcessor
end
class MethodBasedSexpProcessor < SexpProcessor
end
class Object < BasicObject
end
class SexpProcessorError < StandardError
end
class UnsupportedNodeError < SexpProcessorError
end
class UnknownNodeError < SexpProcessorError
end
class NotEmptyError < SexpProcessorError
end
class SexpTypeError < SexpProcessorError
end
