# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simplecov/all/simplecov.rbi
#
# simplecov-0.22.0

module SimpleCov
  extend SimpleCov::Configuration
end
module SimpleCov::Formatter
end
class SimpleCov::Formatter::MultiFormatter
end
module SimpleCov::Formatter::MultiFormatter::InstanceMethods
end
module SimpleCov::Configuration
end
class SimpleCov::CoverageStatistics
end
module SimpleCov::ExitCodes
end
module SimpleCov::ExitCodes::ExitCodeHandling
end
class SimpleCov::ExitCodes::MaximumCoverageDropCheck
end
class SimpleCov::ExitCodes::MinimumCoverageByFileCheck
end
class SimpleCov::ExitCodes::MinimumOverallCoverageCheck
end
class SimpleCov::Profiles < Hash
end
class SimpleCov::SourceFile
end
class SimpleCov::SourceFile::Line
end
class SimpleCov::SourceFile::Branch
end
class SimpleCov::FileList
  extend Forwardable
  include Enumerable
end
class SimpleCov::Result
  extend Forwardable
end
class SimpleCov::Filter
end
class SimpleCov::StringFilter < SimpleCov::Filter
end
class SimpleCov::RegexFilter < SimpleCov::Filter
end
class SimpleCov::BlockFilter < SimpleCov::Filter
end
class SimpleCov::ArrayFilter < SimpleCov::Filter
end
class SimpleCov::Formatter::SimpleFormatter
end
module SimpleCov::LastRun
end
class SimpleCov::LinesClassifier
end
module SimpleCov::ResultMerger
end
module SimpleCov::CommandGuesser
end
class SimpleCov::ResultAdapter
end
module SimpleCov::Combine
end
module SimpleCov::Combine::BranchesCombiner
end
module SimpleCov::Combine::FilesCombiner
end
module SimpleCov::Combine::LinesCombiner
end
module SimpleCov::Combine::ResultsCombiner
end
module SimpleCov::UselessResultsRemover
end
module SimpleCov::SimulateCoverage
end
