# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/thor/all/thor.rbi
#
# thor-1.4.0

class Thor
end
module Thor::Actions
end
class Thor::Actions::EmptyDirectory
end
class Thor::Actions::CreateFile < Thor::Actions::EmptyDirectory
end
class Thor::Actions::CreateLink < Thor::Actions::CreateFile
end
class Thor::Actions::Directory < Thor::Actions::EmptyDirectory
end
class Thor::Actions::CapturableERB < ERB
end
class Thor::Actions::InjectIntoFile < Thor::Actions::EmptyDirectory
end
module Thor::Actions::ClassMethods
end
class Thor::Group
  extend Thor::Base::ClassMethods
  extend Thor::Invocation::ClassMethods
  include Thor::Base
  include Thor::Invocation
  include Thor::Shell
end
