# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-reader/all/tty-reader.rbi
#
# tty-reader-0.9.0

module TTY
end
class TTY::Reader
  extend Wisper::Publisher::ClassMethods
  include Wisper::Publisher
end
class TTY::Reader::History
  extend Forwardable
  include Enumerable
end
class TTY::Reader::Line
end
module TTY::Reader::Keys
end
class TTY::Reader::Key < Anonymous_Struct_9
end
class TTY::Reader::KeyEvent < Anonymous_Struct_10
end
class TTY::Reader::Mode
end
class TTY::Reader::Console
end
class TTY::Reader::WinConsole
end
class TTY::Reader::InputInterrupt < Interrupt
end
