# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-prompt/all/tty-prompt.rbi
#
# tty-prompt-0.23.1

module TTY
end
class TTY::Prompt
  extend Forwardable
end
class TTY::Prompt::AnswersCollector
end
module TTY::Prompt::Const
end
class TTY::Prompt::ConverterRegistry
  extend Forwardable
end
module TTY::Prompt::ConverterDSL
end
module TTY::Prompt::Converters
  extend TTY::Prompt::ConverterDSL
end
class TTY::Prompt::Result
end
class TTY::Prompt::Result::Success < TTY::Prompt::Result
end
class TTY::Prompt::Result::Failure < TTY::Prompt::Result
end
class TTY::Prompt::Evaluator
end
class TTY::Prompt::Question
  include TTY::Prompt::Question::Checks
end
class TTY::Prompt::Question::Modifier
end
class TTY::Prompt::Question::Validation
end
module TTY::Prompt::Question::Checks
end
class TTY::Prompt::Question::Checks::CheckModifier
end
class TTY::Prompt::Question::Checks::CheckRange
end
class TTY::Prompt::Question::Checks::CheckValidation
end
class TTY::Prompt::Question::Checks::CheckDefault
end
class TTY::Prompt::Question::Checks::CheckRequired
end
class TTY::Prompt::Question::Checks::CheckConversion
end
module TTY::Utils
end
class TTY::Prompt::Question::UndefinedSetting
end
class TTY::Prompt::ConfirmQuestion < TTY::Prompt::Question
end
class TTY::Prompt::Error < StandardError
end
class TTY::Prompt::ConfigurationError < TTY::Prompt::Error
end
class TTY::Prompt::ConversionError < TTY::Prompt::Error
end
class TTY::Prompt::ValidationCoercion < TTY::Prompt::Error
end
class TTY::Prompt::ArgumentRequired < TTY::Prompt::Error
end
class TTY::Prompt::ArgumentValidation < TTY::Prompt::Error
end
class TTY::Prompt::InvalidArgument < TTY::Prompt::Error
end
class TTY::Prompt::ConversionAlreadyDefined < TTY::Prompt::Error
end
class TTY::Prompt::UnsupportedConversion < TTY::Prompt::Error
end
class TTY::Prompt::Choice
end
class TTY::Prompt::Choices
  extend Forwardable
  include Enumerable
end
class TTY::Prompt::Expander
end
class TTY::Prompt::Paginator
end
class TTY::Prompt::BlockPaginator < TTY::Prompt::Paginator
end
class TTY::Prompt::EnumList
end
class TTY::Prompt::Timer
end
class TTY::Prompt::Keypress < TTY::Prompt::Question
end
class TTY::Prompt::List
end
class TTY::Prompt::SelectedChoices
  include Enumerable
end
class TTY::Prompt::MultiList < TTY::Prompt::List
end
module TTY::Prompt::Symbols
end
class TTY::Prompt::Multiline < TTY::Prompt::Question
end
class TTY::Prompt::MaskQuestion < TTY::Prompt::Question
end
class TTY::Prompt::Slider
end
class TTY::Prompt::Statement
end
class TTY::Prompt::Distance
end
class TTY::Prompt::Suggestion
end
