# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-cursor/all/tty-cursor.rbi
#
# tty-cursor-0.7.1

module TTY
end
module TTY::Cursor
end
