# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tty-color/all/tty-color.rbi
#
# tty-color-0.6.0

module TTY
end
module TTY::Color
  extend TTY::Color
end
class TTY::Color::Mode
end
class TTY::Color::Support
end
module TTY::Color::NoValue
end
