# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/tzinfo/all/tzinfo.rbi
#
# tzinfo-2.0.6

module TZInfo
end
module TZInfo::RubyCoreSupport
end
class TZInfo::StringDeduper
end
class TZInfo::ConcurrentStringDeduper < TZInfo::StringDeduper
end
class TZInfo::UnaryMinusGlobalStringDeduper
end
class TZInfo::Timestamp
  include Comparable
end
module TZInfo::WithOffset
end
class TZInfo::DateTimeWithOffset < DateTime
  include TZInfo::WithOffset
end
class TZInfo::TimeWithOffset < Time
  include TZInfo::WithOffset
end
class TZInfo::TimestampWithOffset < TZInfo::Timestamp
  include TZInfo::WithOffset
end
class TZInfo::TimezoneOffset
end
class TZInfo::TimezoneTransition
end
class TZInfo::TransitionRule
end
class TZInfo::DayOfYearTransitionRule < TZInfo::TransitionRule
end
class TZInfo::AbsoluteDayOfYearTransitionRule < TZInfo::DayOfYearTransitionRule
end
class TZInfo::JulianDayOfYearTransitionRule < TZInfo::DayOfYearTransitionRule
end
class TZInfo::DayOfWeekTransitionRule < TZInfo::TransitionRule
end
class TZInfo::DayOfMonthTransitionRule < TZInfo::DayOfWeekTransitionRule
end
class TZInfo::LastDayOfMonthTransitionRule < TZInfo::DayOfWeekTransitionRule
end
class TZInfo::AnnualRules
end
module TZInfo::DataSources
end
class TZInfo::DataSources::TimezoneInfo
end
class TZInfo::DataSources::DataTimezoneInfo < TZInfo::DataSources::TimezoneInfo
end
class TZInfo::DataSources::LinkedTimezoneInfo < TZInfo::DataSources::TimezoneInfo
end
class TZInfo::DataSources::ConstantOffsetDataTimezoneInfo < TZInfo::DataSources::DataTimezoneInfo
end
class TZInfo::DataSources::TransitionsDataTimezoneInfo < TZInfo::DataSources::DataTimezoneInfo
end
class TZInfo::DataSources::CountryInfo
end
class TZInfo::DataSources::InvalidPosixTimeZone < StandardError
end
class TZInfo::DataSources::PosixTimeZoneParser
end
class TZInfo::DataSources::InvalidZoneinfoFile < StandardError
end
class TZInfo::DataSources::ZoneinfoReader
end
class TZInfo::InvalidDataSource < StandardError
end
class TZInfo::DataSourceNotFound < StandardError
end
class TZInfo::DataSource
end
class TZInfo::DataSources::TZInfoDataNotFound < StandardError
end
class TZInfo::DataSources::RubyDataSource < TZInfo::DataSource
end
class TZInfo::DataSources::InvalidZoneinfoDirectory < StandardError
end
class TZInfo::DataSources::ZoneinfoDirectoryNotFound < StandardError
end
class TZInfo::DataSources::ZoneinfoDataSource < TZInfo::DataSource
end
class TZInfo::TimezonePeriod
end
class TZInfo::OffsetTimezonePeriod < TZInfo::TimezonePeriod
end
class TZInfo::TransitionsTimezonePeriod < TZInfo::TimezonePeriod
end
class TZInfo::AmbiguousTime < StandardError
end
class TZInfo::PeriodNotFound < StandardError
end
class TZInfo::InvalidTimezoneIdentifier < StandardError
end
class TZInfo::UnknownTimezone < StandardError
end
class TZInfo::Timezone
  include Comparable
end
class TZInfo::InfoTimezone < TZInfo::Timezone
end
class TZInfo::DataTimezone < TZInfo::InfoTimezone
end
class TZInfo::LinkedTimezone < TZInfo::InfoTimezone
end
class TZInfo::TimezoneProxy < TZInfo::Timezone
end
class TZInfo::InvalidCountryCode < StandardError
end
class TZInfo::Country
  include Comparable
end
class TZInfo::CountryTimezone
end
module TZInfo::Format2
end
class TZInfo::Format2::CountryDefiner
end
class TZInfo::Format2::CountryIndexDefiner
end
module TZInfo::Format2::CountryIndexDefinition
end
module TZInfo::Format2::CountryIndexDefinition::ClassMethods
end
class TZInfo::Format2::TimezoneDefiner
end
module TZInfo::Format2::TimezoneDefinition
end
module TZInfo::Format2::TimezoneDefinition::ClassMethods
end
class TZInfo::Format2::TimezoneIndexDefiner
end
module TZInfo::Format2::TimezoneIndexDefinition
end
module TZInfo::Format2::TimezoneIndexDefinition::ClassMethods
end
module TZInfo::Format1
end
class TZInfo::Format1::CountryDefiner < TZInfo::Format2::CountryDefiner
end
module TZInfo::Format1::CountryIndexDefinition
end
module TZInfo::Format1::CountryIndexDefinition::ClassMethods
end
class TZInfo::Format1::TimezoneDefiner < TZInfo::Format2::TimezoneDefiner
end
module TZInfo::Format1::TimezoneDefinition
end
module TZInfo::Format1::TimezoneDefinition::ClassMethods
end
module TZInfo::Format1::TimezoneIndexDefinition
end
module TZInfo::Format1::TimezoneIndexDefinition::ClassMethods
end
