# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/unicode-display_width/all/unicode-display_width.rbi
#
# unicode-display_width-3.1.5

module Unicode
end
class Unicode::DisplayWidth
end
module Unicode::DisplayWidth::EmojiSupport
end
