# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/uri/all/uri.rbi
#
# uri-1.0.3

module URI
end
module URI::RFC2396_REGEXP
end
module URI::RFC2396_REGEXP::PATTERN
end
class URI::RFC2396_Parser
  include URI::RFC2396_REGEXP
end
class URI::RFC3986_Parser
end
module URI::Util
end
module URI::Schemes
end
class URI::Error < StandardError
end
class URI::InvalidURIError < URI::Error
end
class URI::InvalidComponentError < URI::Error
end
class URI::BadURIError < URI::Error
end
module Kernel
end
class URI::Generic
  include URI
end
class URI::File < URI::Generic
end
class URI::FTP < URI::Generic
end
class URI::HTTP < URI::Generic
end
class URI::HTTPS < URI::HTTP
end
class URI::LDAP < URI::Generic
end
class URI::LDAPS < URI::LDAP
end
class URI::MailTo < URI::Generic
  include URI::RFC2396_REGEXP
end
class URI::WS < URI::Generic
end
class URI::WSS < URI::WS
end
