# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/wisper/all/wisper.rbi
#
# whisper-2.0.1

module Whisper
end
class Whisper::Configuration
end
class Whisper::Configuration::Broadcasters
  extend Forwardable
end
module Whisper::Publisher
end
module Whisper::Publisher::ClassMethods
end
module Whisper::ValueObjects
end
class Whisper::ValueObjects::Prefix < String
end
class Whisper::ValueObjects::Events
end
class Whisper::Registration
end
class Whisper::ObjectRegistration < Whisper::Registration
end
class Whisper::BlockRegistration < Whisper::Registration
end
class Whisper::GlobalListeners
  extend Singleton::SingletonClassMethods
  include Singleton
end
class Whisper::TemporaryListeners
end
module Whisper::Broadcasters
end
class Whisper::Broadcasters::SendBroadcaster
end
class Whisper::Broadcasters::LoggerBroadcaster
end
