# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/wisper/all/wisper.rbi
#
# wisper-2.0.1

module Wisper
end
class Wisper::Configuration
end
class Wisper::Configuration::Broadcasters
  extend Forwardable
end
module Wisper::Publisher
end
module Wisper::Publisher::ClassMethods
end
module Wisper::ValueObjects
end
class Wisper::ValueObjects::Prefix < String
end
class Wisper::ValueObjects::Events
end
class Wisper::Registration
end
class Wisper::ObjectRegistration < Wisper::Registration
end
class Wisper::BlockRegistration < Wisper::Registration
end
class Wisper::GlobalListeners
  extend Singleton::SingletonClassMethods
  include Singleton
end
class Wisper::TemporaryListeners
end
module Wisper::Broadcasters
end
class Wisper::Broadcasters::SendBroadcaster
end
class Wisper::Broadcasters::LoggerBroadcaster
end
