AllCops:
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

plugins:
  - rubocop-rspec
  - rubocop-performance
